source_path: ./source/競賽資料集/reference_text
question_path: ./source/競賽資料集/dataset/preliminary/questions_example.json
answer_path: ./source/競賽資料集/dataset/preliminary/ground_truths_example.json

output_dir: ./output
data_type: ocr_text
retriever: sparse
clean_text: True
embedding_model: bge-m3
max_tokens: 4096
stride: 3072

scorer: True
