source_path: ./source/競賽資料集/reference_text_adobe
question_path: ./source/競賽資料集/dataset/preliminary/questions_example.json
answer_path: ./source/競賽資料集/dataset/preliminary/ground_truths_example.json

output_dir: ./output_adobe
data_type: ocr_text
retriever: cosine_similarity
clean_text: True
embedding_model: bge-large-zh-v1.5
max_tokens: 128
stride: 64

scorer: True
