source_path: ./source/競賽資料集/reference_text
question_path: ./source/競賽資料集/dataset/preliminary/questions_example.json
answer_path: ./source/競賽資料集/dataset/preliminary/ground_truths_example.json

output_dir: ./output
data_type: ocr_text
retriever: cosine_similarity
embedding_model: bge-m3
clean_text: True
scorer: True
