source_path: ./source/競賽資料集/reference_text_adobe
question_path: ./source/競賽資料集/dataset/preliminary/questions_example.json
answer_path: ./source/競賽資料集/dataset/preliminary/ground_truths_example.json

output_dir: ./output_adobe
data_type: ocr_text
retriever: bm25
tokenizer: ckip
clean_text: True
scorer: True
