source_path: ./source/競賽資料集/reference_text
question_path: ./source/競賽資料集/dataset/preliminary/questions_example.json
answer_path: ./source/競賽資料集/dataset/preliminary/ground_truths_example.json

output_dir: ./output
data_type: ocr_text
clean_text: True

retriever_v2: bm25
tokenizer: ckip
normalize: minmax

retriever_v3: cosine_similarity
embedding_model: bge-m3
max_tokens: 256
stride: 128

alpha: 0.09
beta: 0.5
scorer: True
