source_path: ./source/競賽資料集/reference_text
question_path: ./source/競賽資料集/dataset/preliminary/questions_example.json
answer_path: ./source/競賽資料集/dataset/preliminary/ground_truths_example.json

output_dir: ./output
data_type: ocr_text

clean_text: True
reranker: bge-reranker-v2-m3
max_tokens: 2048
stride: 512

scorer: True
